// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_proteoCpp_RCPPEXPORTS_H_GEN_
#define RCPP_proteoCpp_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace proteoCpp {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("proteoCpp", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("proteoCpp", "_proteoCpp_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in proteoCpp");
            }
        }
    }

    inline List par_distC(IntegerVector cols, List mat) {
        typedef SEXP(*Ptr_par_distC)(SEXP,SEXP);
        static Ptr_par_distC p_par_distC = NULL;
        if (p_par_distC == NULL) {
            validateSignature("List(*par_distC)(IntegerVector,List)");
            p_par_distC = (Ptr_par_distC)R_GetCCallable("proteoCpp", "_proteoCpp_par_distC");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_par_distC(Shield<SEXP>(Rcpp::wrap(cols)), Shield<SEXP>(Rcpp::wrap(mat)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<List >(rcpp_result_gen);
    }

}

#endif // RCPP_proteoCpp_RCPPEXPORTS_H_GEN_
