# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parallel distance calculations.
#'
#' @param cols A range of column indexes.
#' @param mat A logical matrix (split into lists).
#' @export
par_distC <- function(cols, mat) {
    .Call(`_proteoCpp_par_distC`, cols, mat)
}

#' Extracts the lower triangular of a logical distance matrix.
#'
#' @param m A logical matrix.
#' @export
to_lgldistC <- function(m) {
    .Call(`_proteoCpp_to_lgldistC`, m)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_proteoCpp_RcppExport_registerCCallable', PACKAGE = 'proteoCpp')
})
